# Generated by Django 5.1.14 on 2026-01-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
