# Generated by Django 5.1.15 on 2026-02-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_guest_is_blocked_blockedvisitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='todaysvisiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitername', models.CharField(max_length=100)),
                ('dateofvisit', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='visited photo')),
            ],
        ),
    ]
