# Generated by Django 5.1.15 on 2026-02-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_todaysvisiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaysvisiter',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
