# Generated by Django 5.1.15 on 2026-02-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_todaysvisiter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaysvisiter',
            name='emotion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
